version: '3'
services:
  mariadb:
    image: 'mariadb:latest'
    container_name: 'mariadb'
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
#    env_file:
#    - mariadb.env
    volumes:
      - config:/etc/mysql/conf.d
      - datadir:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
    - mariadb
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
    - 40080:80
    - 48183:8183
volumes:
  config:
  datadir: